### ISSUE TITLE
New Annotation Class & Layer

### ISSUE THREAD

**Issue by slee-ie** [sung-park/sensor_data_labeler#29]
오늘 (11.13) 메일로 말씀드린 수정 요청 사항들을 말씀해주신 대로 이슈로 각각 간단하게 달아두도록 하겠습니다 .

< 라벨링 프로그램 수정 요청 사항 >
라벨링 클래스 추가 및 기능 추가에 대해서 다음과 같이 요청드리고자 합니다.

(1) 추가 클래스 
a. petting (보호자가 쓰다듬음)
b. etc (기타) 
c. uncertain (불확실함) :

(2) 클래스레이어 추가 
현재는 자세, 행동, 소리로 클래스레어이가 구분되어 있는데,
행동의 경우 레이어를 2개를 두어 
위의 두 개 경우 등 행동의 구분이 어려운 패턴에 
두개 행동을 모두 라벨링하도록 하면 이 부분이 해결될 것으로 보입니다.
이에 행동 클래스를 중복해서 라벨링할 수 있도록 보조 행동 레이어를 추가해주시기 부탁드립니다.

**Comment by sung-park** [comment]
(1) 추가 클래스
a. petting (보호자가 쓰다듬음)
b. etc (기타)
c. uncertain (불확실함)

위의 3개 항목은 Activity에 추가되면 되는 것이죠? etc와 uncertain은 라벨러 입장에서 어떻게 다른 것일까요? 무슨 행동하는지 알겠는데 없으면 etc, 아니면 잘 안보이거나 정말 모르겠으면 uncertain 정도로 이해하면 될까요?

**Comment by sung-park** [comment]
> > (1) 추가 클래스
> > a. petting (보호자가 쓰다듬음)
> > b. etc (기타)
> > c. uncertain (불확실함)
> 
> 위의 3개 항목은 Activity에 추가되면 되는 것이죠? etc와 uncertain은 라벨러 입장에서 어떻게 다른 것일까요? 무슨 행동하는지 알겠는데 없으면 etc, 아니면 잘 안보이거나 정말 모르겠으면 uncertain 정도로 이해하면 될까요?

상세한 내용 메일로 주셨군요. 확인하였습니다.

**Comment by sung-park** [comment]
> (1) 추가 클래스
> a. petting (보호자가 쓰다듬음)
> b. etc (기타)
> c. uncertain (불확실함) :

f4bb19d5d0787c7bc9c7dffb7fd2b9db8173c77c

**Comment by sung-park** [comment]
현재 시점에서 가장 빠르게 구현 가능한 형태로 추가했습니다. 확인 부탁드립니다.
https://github.com/sung-park/sensor_data_labeler/releases/tag/1.5.0
