### ISSUE TITLE
Additional Functions

### ISSUE THREAD

**Issue by slee-ie** [sung-park/sensor_data_labeler#31]
(4) 기타 프로그램 기능 추가 및 수정 요청 사항

여기에 몇가지 수정되거나 기능이 추가되면 훨씬 사용이 용이할 것 같아 아래에 리스트업 하였습니다.
반드시 필수는 아닙니다만, 추가되면 사용성 개선에 크게 도움이 될 것 같습니다.

a. 장영석 프로님에 언급해주신 바와 같이
센서 배경이 검은색이어서 눈에 피로감이 많이 드는 것 같습니다. 
흰색 배경에 굵은 센서 라인이면 좋겠습니다.

b. 현재 속도를 조절할 수 없는데 
영상 및 센서를 follow 하는 속도를 느리게하거나 빠르게 할 수 있도록 조절할 수 있다면 
구간의 시작/끝 점을 조절하거나, 전체 패턴을 browsing 하는데 크게 도움이 되겠습니다.

c. 영상에서 보여지는 시점을 센서에서 vertical line으로 보여주는데, 
센서 전체가 움직이지는 않아서 해당 시점의 패턴을 보려면 드래그앤드롭으로 계속해서 움직여줘야 합니다.
스크롤바가 추가되거나 쉽게 센서를 넘길 수 있는 기능이 추가되면 좋겠습니다.

d. 커서 키 등으로 특정 시간 (1초, 0.5초 등) 만큼 앞 뒤로 넘길 수 있도록 하는 단축키가 있으면 좋겠습니다.

e. 영상 크기를 크게 조정할 수 있는 방법이 있을까요?

f. 1.3.2 버전에서, 라벨링 클래스에 "걷기"가 두번 추가 되어있습니다. 확인 및 제거를 부탁드립니다. 

g. 현재 프로그램에 노트를 남기는 부분이 있는데, 노트를 남기면 ann 파일과 함께 저장되는지 여부 확인하고 싶습니다.
데이터마다 노트를 따로 남길 수 있는 기능이 있으면, 해당 데이터 라벨링을 작업하면서 부딪힌 이슈
(e.g. 머리를 손으로 비비는 것을 '기타' 클래스로 라벨링 함)
를 작성하고 나중에 참고하는데 도움이 될 것 같습니다.

**Comment by sung-park** [comment]
> a. 장영석 프로님에 언급해주신 바와 같이
> 센서 배경이 검은색이어서 눈에 피로감이 많이 드는 것 같습니다.
> 흰색 배경에 굵은 센서 라인이면 좋겠습니다.

아주 단순한 수정일 줄 알았는데 line width를 2 이상으로 바꾸면 급격한 성능 저하가 있어 살펴보고 있습니다....
https://github.com/pyqtgraph/pyqtgraph/issues/533

일단 느낌은 아래와 같습니다.
![image](https://github.com/sung-park/sensor_data_labeler/assets/31734973/2aa20951-88a9-4d97-bc90-37c9a2ca1663)

**Comment by sung-park** [comment]
@slee-ie 
![image](https://github.com/sung-park/sensor_data_labeler/assets/31734973/93b22d5f-3157-43ab-844a-23567193baec)
일단 두께를 포기하면 위와 같은 느낌입니다. 색상이 그다지 마음에 들진 않은데 가독성이 괜찮으신지와 혹시 원하시는 색상 알려주시면 감사하겠습니다.

**Comment by sung-park** [comment]
> g. 현재 프로그램에 노트를 남기는 부분이 있는데, 노트를 남기면 ann 파일과 함께 저장되는지 여부 확인하고 싶습니다.
> 데이터마다 노트를 따로 남길 수 있는 기능이 있으면, 해당 데이터 라벨링을 작업하면서 부딪힌 이슈
> (e.g. 머리를 손으로 비비는 것을 '기타' 클래스로 라벨링 함)
> 를 작성하고 나중에 참고하는데 도움이 될 것 같습니다.

네 말씀하신 의도로 note 필드 추가하였고 ann 파일에 함께 저장됩니다.

![image](https://github.com/sung-park/sensor_data_labeler/assets/31734973/ae495fa8-2c22-4e5b-a3af-b1e8342c0501)

**Comment by sung-park** [comment]
> a. 장영석 프로님에 언급해주신 바와 같이
> 센서 배경이 검은색이어서 눈에 피로감이 많이 드는 것 같습니다.
> 흰색 배경에 굵은 센서 라인이면 좋겠습니다.

우선 아래와 같이 반영하고 의견 주시면 재수정하겠습니다.
![image](https://github.com/sung-park/sensor_data_labeler/assets/31734973/62d1c3d5-8d92-4974-a95a-28d695d7f532)

**Comment by sung-park** [comment]
> b. 현재 속도를 조절할 수 없는데
> 영상 및 센서를 follow 하는 속도를 느리게하거나 빠르게 할 수 있도록 조절할 수 있다면
> 구간의 시작/끝 점을 조절하거나, 전체 패턴을 browsing 하는데 크게 도움이 되겠습니다.

https://github.com/sung-park/sensor_data_labeler/issues/32

별도 이슈로 등록했습니다.

**Comment by sung-park** [comment]
> f. 1.3.2 버전에서, 라벨링 클래스에 "걷기"가 두번 추가 되어있습니다. 확인 및 제거를 부탁드립니다.

631ad903031fe87664aa929dcc9f591c4b02db0f 로 제거했습니다. 확인 감사합니다.

**Comment by sung-park** [comment]
> e. 영상 크기를 크게 조정할 수 있는 방법이 있을까요?

레이아웃 조정은 좀 큰 이슈라 별도 이슈 생성하였습니다. https://github.com/sung-park/sensor_data_labeler/issues/33

**Comment by sung-park** [comment]
> c. 영상에서 보여지는 시점을 센서에서 vertical line으로 보여주는데,
> 센서 전체가 움직이지는 않아서 해당 시점의 패턴을 보려면 드래그앤드롭으로 계속해서 움직여줘야 합니다.
> 스크롤바가 추가되거나 쉽게 센서를 넘길 수 있는 기능이 추가되면 좋겠습니다.

버티컬 라인이 영상 밖으로 벗어나면 가운데쯤 오도록 PlotWidget을 조정토록 했습니다.

> d. 커서 키 등으로 특정 시간 (1초, 0.5초 등) 만큼 앞 뒤로 넘길 수 있도록 하는 단축키가 있으면 좋겠습니다.

좌우키를 누르면 각각 0.5초씩 이동하도록 했습니다. 이동 크기 변경이 필요하면 써보시고 알려주세요.

58f338ea32dea988be65d1a545ef73a141a5abc9

**Comment by sung-park** [comment]
자동 스크롤이 오히려 어지럽다는 사용자도 있어서 우선 옵션을 추가하여 사용자가 원하지 않을 경우 해당 기능 동작하지 않도록 했습니다.

4510b873ae4c1fb06c60619b18c54179256636fb

![image](https://github.com/sung-park/sensor_data_labeler/assets/31734973/f1a4120d-c577-4c88-a128-e80ea665c9d7)

**Comment by sung-park** [comment]
처리하지 않는 것들은 별도 이슈로 등록하여 이 이슈는 닫도록 하겠습니다.
